typography_spectrum: 1
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Capital Services
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sample Website
purpose: []
